<?php
/**
 * @file yarn_alters.module
 * TODO: Enter file description here.
 */

/**
 * Implements of hook_theme().
 */
function yarn_alters_theme($existing, $type, $theme, $path) {
  return array(
    'yarn_alters_products' => array(
      'file' => 'yarn_alters.theme.inc',
      'variables' => array(
        'fields'     => NULL,
        'label'      => NULL,
        'field_name' => NULL,
      ),
    ),
  );
}